# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b3f06d8c699527ffe70bf4222dcd143c6c7d595fb7ff3d1380a11ec74709d9dbec981f16f7c3a03b17595b462c828546de3c015e0fe94c78d58503c72a3cbb5

test:
  secret_key_base: 6d9c43edd95f716de9276610bc3322b2f03bf60a5064fa6e04a456481ce2da4c49f0fe0840e2fce0e5bfc25a9804c5e295863e104e9a38d813c0d708a4e7852e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
